/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
          950: "#052e16",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Nuevos tonos de verde personalizados
        caravalia: {
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
          950: "#052e16",
        },
        "surface-tint": "#376757",
        "secondary-container": "#d4e7dd",
        "on-tertiary-fixed-variant": "#693a33",
        "on-tertiary": "#ffffff",
        "tertiary": "#4c221c",
        "secondary-fixed": "#d4e7dd",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#e4a399",
        "surface-bright": "#f9f9f8",
        "outline-variant": "#c0c9c3",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#f9f9f8",
        "on-primary-fixed-variant": "#1d4f40",
        "primary-fixed-dim": "#9ed1bd",
        "on-secondary-fixed": "#0f1f19",
        "on-error": "#ffffff",
        "on-primary-container": "#8abda9",
        "surface-variant": "#e1e3e2",
        "surface-container-low": "#f3f4f3",
        "on-secondary-fixed-variant": "#3a4a43",
        "primary-container": "#1b4d3e",
        "surface-container-highest": "#e1e3e2",
        "error": "#ba1a1a",
        "inverse-primary": "#9ed1bd",
        "surface-container": "#edeeed",
        "on-secondary": "#ffffff",
        "primary-fixed": "#baeed9",
        "on-surface": "#191c1c",
        "on-secondary-container": "#576860",
        "on-primary-fixed": "#002117",
        "surface-dim": "#d9dad9",
        "outline": "#707974",
        "on-tertiary-fixed": "#34100b",
        "inverse-on-surface": "#f0f1f0",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3131",
        "tertiary-container": "#673831",
        "tertiary-fixed": "#ffdad5",
        "secondary-fixed-dim": "#b8cbc1",
        "surface-container-high": "#e7e8e7"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "m3-DEFAULT": "1rem",
        "m3-lg": "2rem",
        "m3-xl": "3rem",
        "full": "9999px"
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      boxShadow: {
        soft: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        card: "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
